// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoxmKEJROqIPhbvS3WnHjPg6D9doj33mA',
    appId: '1:223074033601:web:68dc96b0e337e967ec1940',
    messagingSenderId: '223074033601',
    projectId: 'games-5d4f6',
    authDomain: 'games-5d4f6.firebaseapp.com',
    storageBucket: 'games-5d4f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-EVQ0zAvojX62KuyR9yFv6wM-Vrij-Y',
    appId: '1:223074033601:android:5dee41c43e75809bec1940',
    messagingSenderId: '223074033601',
    projectId: 'games-5d4f6',
    storageBucket: 'games-5d4f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN63KmgpniNNbAiauj_ianKOSpTcozt9Y',
    appId: '1:223074033601:ios:f9d92aa721fa0f07ec1940',
    messagingSenderId: '223074033601',
    projectId: 'games-5d4f6',
    storageBucket: 'games-5d4f6.firebasestorage.app',
    iosBundleId: 'com.example.games',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN63KmgpniNNbAiauj_ianKOSpTcozt9Y',
    appId: '1:223074033601:ios:f9d92aa721fa0f07ec1940',
    messagingSenderId: '223074033601',
    projectId: 'games-5d4f6',
    storageBucket: 'games-5d4f6.firebasestorage.app',
    iosBundleId: 'com.example.games',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoxmKEJROqIPhbvS3WnHjPg6D9doj33mA',
    appId: '1:223074033601:web:6305b2e963bf9f65ec1940',
    messagingSenderId: '223074033601',
    projectId: 'games-5d4f6',
    authDomain: 'games-5d4f6.firebaseapp.com',
    storageBucket: 'games-5d4f6.firebasestorage.app',
  );
}
